name: Deploy backend API
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install ssh client
      run: sudo apt-get install openssh-client
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: api.christofferbillman.se
        username: popkr
        password: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/stocken-wiki/server
          git pull
          npm ci
          npm run build
          npm run prod:stop
          npm run prod:start