name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploying to AWS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Debug HOST
        run: echo "HOST is ${AWS_HOST}"
        env:
          AWS_HOST: ${{ secrets.AWS_INSTANCE }}
      - name: Debug USER
        run: echo "USER is ${AWS_USER}"
        env:
            AWS_USER: ${{ secrets.AWS_USERNAME }}
      - name: Deploying application to EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.AWS_KEY }}
          AWS_HOST: ${{ secrets.AWS_INSTANCE }}
          AWS_USERNAME: ${{ secrets.AWS_USERNAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_USERNAME}@${AWS_HOST} bash deploy.sh
